### ISSUE TITLE
Unrecognized format error: could not open file /var/cache/pacman/pkg/*

### ISSUE THREAD

**Issue by MontFox** [yuk7/ArchWSL#110]
**Describe the issue**
When attempting to run `sudo pacman -Syu` or `sudo pacman -S` I receive 

> could not open file /var/cache/pacman/pkg/pkg.pkg.tar.zst: Unrecognized archive format
> error: failed to commit transaction (cannot open package file)
> Errors occurred, no packages were upgraded.

**To Reproduce**

I have fresh installed from zip to both Documents and a folder on the desktop.
1.) Run Arch.exe as administrator
2.) set root passwd and default user per wiki
3.) Logged in as created user, run `sudo pacman-key --init  ` and `sudo pacman-key --populate`

**Expected behavior**

after refreshing keys, pacman should be able to install and update packages

**Actual behavior**

Run `sudo pacman -S libusb`

```
[user@user ~]$ sudo pacman -S libusb
resolving dependencies...
looking for conflicting packages...
:: systemd-libs and libsystemd are in conflict. Remove libsystemd? [y/N] y

Packages (3) libsystemd-238.133-4 [removal]  systemd-libs-245-3  libusb-1.0.23-2

Total Download Size:   0.55 MiB
Total Installed Size:  1.94 MiB
Net Upgrade Size:      0.32 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'systemd-libs-245-3-x86_64.pkg.tar.zst' from mirrors.evowise.com : The requested URL returned error: 404
 systemd-libs-245-3-x86_64                      504.7 KiB  59.9K/s 00:08 [########################################] 100%
 libusb-1.0.23-2-x86_64                          57.0 KiB  77.3K/s 00:01 [########################################] 100%
(2/2) checking keys in keyring                                           [########################################] 100%
(2/2) checking package integrity                                         [########################################] 100%
(2/2) loading package files                                              [########################################] 100%
error: could not open file /var/cache/pacman/pkg/systemd-libs-245-3-x86_64.pkg.tar.zst: Unrecognized archive format
error: failed to commit transaction (cannot open package file)
Errors occurred, no packages were upgraded.
```

Running sudo pacman -Syu will also prompt to replace libsystemd with core/systemd-libs,
it will proceed to update the packages then not be able to install them with the same error as in the title. Do I have a permissions issue going on? Thanks in advanced.

**Comment by MontFox** [comment]
After following 

`wget https://pkgbuild.com/~eschwartz/repo/x86_64-extracted/pacman-static
chmod +x pacman-static
sudo ./pacman-static -S libusb`

I was able to install libusb, currently running `sudo ./pacman-static -Syyu` (very slow internet speed... as you can tell. 77.3kb/s lol)

Wondering if this will fix it or if I will need to mess around with this pacman-static some more. Forgive me, I'm not very familiar with Arch's package manager.

**Comment by batot1** [comment]
Not working.
$ wget https://pkgbuild.com/~eschwartz/repo/x86_64-extracted/pacman-static chmod +x pacman-static sudo ./pacman-static -S libusb
--2023-01-10 14:02:54--  https://pkgbuild.com/~eschwartz/repo/x86_64-extracted/pacman-static
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving pkgbuild.com (pkgbuild.com)... 78.46.178.133, 2a01:4f8:c2c:51e2::1
Connecting to pkgbuild.com (pkgbuild.com)|78.46.178.133|:443... connected.
ERROR: The certificate of 'pkgbuild.com' is not trusted.
ERROR: The certificate of 'pkgbuild.com' has expired.
--2023-01-10 14:02:55--  http://chmod/
Resolving chmod (chmod)... failed: Name or service not known.
wget: unable to resolve host address 'chmod'
--2023-01-10 14:02:55--  http://+x/
Resolving +x (+x)... failed: Name or service not known.
wget: unable to resolve host address '+x'
--2023-01-10 14:02:55--  http://pacman-static/
Resolving pacman-static (pacman-static)... failed: Name or service not known.
wget: unable to resolve host address 'pacman-static'
--2023-01-10 14:02:55--  http://sudo/
Resolving sudo (sudo)... failed: Name or service not known.
wget: unable to resolve host address 'sudo'
--2023-01-10 14:02:55--  http://./pacman-static
Resolving . (.)... failed: No address associated with hostname.
wget: unable to resolve host address '.'
--2023-01-10 14:02:55--  http://libusb/
Resolving libusb (libusb)... failed: Name or service not known.
wget: unable to resolve host address 'libusb'
$ ls
$

**Comment by batot1** [comment]
> Also the pacman-static link is dead.

I don't this so:
" Last Updated: 	2022-11-18 16:51 (UTC)"

**Comment by batot1** [comment]
Ok i know how repair this for any person who will be read this:

```
Must add in pacman.conf this:
[pacman-static]
SigLevel = Required
Server = https://pkgbuild.com/~morganamilo/$repo/$arch

```
form https://aur.archlinux.org/packages/pacman-static
but because you get error when try pacman -Syu:
]$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archlinuxfr is up to date
 pacman-static                                                                                                    544.0   B  0.00B/s 00:00 [####################################################################################] 100%
 pacman-static.sig                                                                                                566.0   B  0.00B/s 00:00 [####################################################################################] 100%
error: pacman-static: key "F850562FCDA369F80D33000AE48D0A8326DE47C5" is unknown
error: key "F850562FCDA369F80D33000AE48D0A8326DE47C5" could not be looked up remotely
error: failed to update pacman-static (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases

You must replace "SigLevel = Required" for "SigLevel = Never".
And...
]$ sudo pacman -S pacman-static
resolving dependencies...
looking for conflicting packages...

Packages (1) pacman-static-6.0.1-2

Total Download Size:    2.76 MiB
Total Installed Size:  16.79 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 pacman-static-6.0.1-2-x86_64                                                                                       2.8 MiB  1230K/s 00:02 [####################################################################################] 100%
(1/1) checking keys in keyring                                                                                                             [####################################################################################] 100%
(1/1) checking package integrity                                                                                                           [####################################################################################] 100%
(1/1) loading package files                                                                                                                [####################################################################################] 100%
(1/1) checking for file conflicts                                                                                                          [####################################################################################] 100%
(1/1) checking available disk space                                                                                                        [####################################################################################] 100%
:: Processing package changes...
(1/1) installing pacman-static                                                                                                             [####################################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

voile - working.
And now test pacman-static -Syu
[...]
Total Installed Size:  8033.99 MiB
Net Upgrade Size:      2322.55 MiB

:: Proceed with installation? [Y/n]
(1127/1127) checking keys in keyring                                                                                                       [####################################################################################] 100%
(1127/1127) checking package integrity                                                                                                     [####################################################################################] 100%
(1127/1127) loading package files                                                                                                          [####################################################################################] 100%
(1127/1127) checking for file conflicts                                                                                                    [####################################################################################] 100%
error: failed to commit transaction (conflicting files)
imath: /usr/lib/libImath.so exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/Iex.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexBaseExc.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexErrnoExc.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexExport.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexForward.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexMacros.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexMathExc.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexMathFloatExc.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexMathIeeeExc.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexNamespace.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IexThrowErrnoExc.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IlmThread.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IlmThreadExport.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IlmThreadForward.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IlmThreadMutex.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IlmThreadNamespace.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IlmThreadPool.h exists in filesystem (owned by ilmbase)
openexr: /usr/include/OpenEXR/IlmThreadSemaphore.h exists in filesystem (owned by ilmbase)
openexr: /usr/lib/libIex.so exists in filesystem (owned by ilmbase)
openexr: /usr/lib/libIlmThread.so exists in filesystem (owned by ilmbase)
Errors occurred, no packages were upgraded.

...and near success but still get error.
