### ISSUE TITLE
i3 and xming shows Blackscreen

### ISSUE THREAD

**Issue by Sicks3c** [yuk7/ArchWSL#122]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
Hello

After following the installation and all the instructions I get almost a black screen
See the screenshot
![Untitled](https://user-images.githubusercontent.com/32225186/81047603-4a476980-8eaa-11ea-893b-13abc65f2051.png)

**To Reproduce**
follow the steps

**Expected behavior**
Getting the same fonts and working as you have

**Screenshots**
Look Above

**Enviroment:**
 - Microsoft Windows [Version 10.0.18362.778]
 - Windows Defender
 - WSL 1
 - ArchWSL 20.4.3.0
 - ZIP
 - Launcher version 
`wsldl, version 20040300
https://git.io/wsldl
`

**Comment by HoshiYamazaki** [comment]
This is due to bad configured `i3` window manager.

**Comment by amiralkizaru** [comment]
Hello
Thanks for reply 
Do you have any good i3 configs that may work ?

**Comment by HoshiYamazaki** [comment]
https://www.reddit.com/r/bashonubuntuonwindows/comments/7zcq4a/why_i3_does_not_display_anything/

i3 is just an Window Manager which you must use with knowledge, if you don't know how to configure it it's just not for you. Install XFCE then.

Or I assume you don't know what you are doing.

**Comment by WyRe** [comment]
@amiralkizaru you don't need a window manager to open graphical apps using xming.

**Comment by amiralkizaru** [comment]
@HoshiYamazaki 
Dude you are rude / stupid as fuck
I managed to make it work with awesome desktop manager 
Learn how to speak and don't throw accusation like a donkey

**Comment by HoshiYamazaki** [comment]
> @HoshiYamazaki
> Dude you are rude / stupid as fuck
> I managed to make it work with awesome desktop manager
> Learn how to speak and don't throw accusation like a donkey

Sorry, I was not rude, you started to offend me for some reason (point me where I did that at first), where providing ready `i3` config file takes for average person just 15 minutes, this is odd for person who has skills in security, but thats not my interest.

I'm gonna report that to github administration if that possible, because being nervous and aggresive teenager is not fine in this world, at all.

Also what is wrong in my advise? Are you similar with i3 keybinds to use that? I just told you in nice way to use XFCE. If you really don't know i3, this is just not for you, like using `vim` (thats why I never use VIM :D).
@yuk7 can you delete that thread, because of `aggresive` behaviour of the author?

**Comment by yuk7** [comment]
@HoshiYamazaki 
I have deleted the comment that attack others.
I am sorry for the delay in dealing with it.

**Comment by HoshiYamazaki** [comment]
> @HoshiYamazaki
> I have deleted the comment that attacks you.
> I am sorry for the delay in dealing with it.

Thats fine, I never wanted to /offend/ anybody, maybe I told this is not nice way, but if somebody don't know what is i3 for, he probably should never use that, since learning keybindings and gettings used to it takes a while.

I don't really remember if wsldl installs `i3` by default because it takes @amiralkizaru in different kind of situation (he could never install `i3` and not know why XServer behaves like that), but still, this is basic knowledge about usage of Linux and switching to other graphical environments.

**Comment by yuk7** [comment]
@HoshiYamazaki 
ArchWSL/wsldl does not install i3 by default.
On the author's screen for this issue, i3status appears to be displayed.
I think the author of the issue lacks an explanation.

**Comment by amiralkizaru** [comment]
@HoshiYamazaki
I use i3 in my latpop in a daily basis when you install it first it looks ugly as fuck but not 80% blackscreen , and I though I'm missing some dependencies since Arch is just installed
Besides you said 
`if you don't know how to configure it it's just not for you`
`Or I assume you don't know what you are doing.`
That is pretty disrespectful buddy
Throwing things like that is unprofessional . I rather being ignored that seeing when I wake up
:)

**Comment by yuk7** [comment]
@amiralkizaru 
Is something displayed in the i3 log?
check
```
DISPLAY=:0 i3
```
in console?

**Comment by yuk7** [comment]
![i3-archwsl](https://user-images.githubusercontent.com/29954265/81501623-5735e400-9314-11ea-98b1-56d57b50e9d6.png)
I tested i3-wm in ArchWSL and WSL1 Win10 2004.
installed `i3`,`xterm` and fonts package

**Comment by HoshiYamazaki** [comment]
> @HoshiYamazaki
> I use i3 in my latpop in a daily basis when you install it first it looks ugly as fuck but not 80% blackscreen , and I though I'm missing some dependencies since Arch is just installed
> Besides you said
> `if you don't know how to configure it it's just not for you`
> `Or I assume you don't know what you are doing.`
> That is pretty disrespectful buddy
> Throwing things like that is unprofessional . I rather being ignored that seeing when I wake up
> :)

Ok, sorry, I assumed you as script kiddie again. I had the same problem with i3 and I don't quite remember how I configured that correctly but probably I wrote my own config and set wallpaper with `feh` script. You should use `gnome-terminator` as terminal for best exprience (for me it works the best way). You could install `zsh` too. Many configs are lying on github. Also use `rofi` for launcher. This is my config:
https://github.com/HoshiYamazaki/wsl-dots

Sorry, I have sometimes bad days where people are trying to get non-sense help without working on it, I know many non-tech or pseudo-tech people which are trying the same, and I get tired this way. Also I sometimes get help like that too, support people are talking me to as non-tech person which drives me crazy.

But this is just some reason to go outside and talk to people, since I'm just tired with nerding as it is and my brain just thinks different after years of sitting at computer, also I don't have many exprience with normal/non-tech persons at all. This is the moment when you think this is time to work on social skills :D

**Comment by amiralkizaru** [comment]
I see what you mean
But remember you should always treat people the same even if they don't know what they are doing
I know the creator of https://github.com/ffuf/ffuf
and they manage a shit ton of issues and they reply super fast even if the questions are dumb as fuck
I hope you work on your social skills
Cheers
