### ISSUE TITLE
Internet or Network suddenly gone. Gibbrish /etc/resolv.conf file

### ISSUE THREAD

**Issue by hemanta212** [yuk7/ArchWSL#140]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
I installed arch from latest appx file. Pacman ran fine. However after few days, network is suddenly gone. Pacman can't connect to mirrors and even ping doesnot work. cat /etc/resolv.conf file returns nothing. The file is filled with gibbrish.

**To Reproduce**
Install Arch from appx file. Try to connect to internet.

**Expected behavior**
The instance should support internet.

**Screenshots**
![image](https://user-images.githubusercontent.com/25475894/85388041-50ca9700-b565-11ea-843b-3b87230085ac.png)
![image](https://user-images.githubusercontent.com/25475894/85388044-52945a80-b565-11ea-9758-fa365217ab74.png)

Second image is content of /etc/resolv.conf file

**Enviroment:**
 - Windows build number: Version 10.0.18362.30
 - Security Software: None
 - WSL version 1/2: WSL1
 - ArchWSL version: 20.4.3.0
 - ArchWSL Installer type zip/appx/other clean/update: appx clean
 - Launcher version [e.g. 19030700] (Type `Arch.exe version` at a Command Prompt): 20040300

**Additional context**
One solution I found is to replace the contents in /etc/resolv.conf file with the contents of /etc/resolv.conf file of other working wsl1 distros.

**Comment by yuk7** [comment]
Rewrite `resolv.conf` with the following contents for enable auto generation:
```
This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
```

Also check that the `/etc/wsl.conf` settings are correct.

**Comment by Alexander-Huang** [comment]
Could you please paste your resolv.conf of wsl1?I have the same issue after switching to wsl2.

**Comment by arlllk** [comment]
Currently there is a bug on Insider WSL2, where the Internet connection gets disconnected after x time

**Comment by PhilDim1** [comment]
resolv.conf gets automatically generated on each instance of wsl2. If you create a file called /etc/wsl.conf with the contents[network]generateResolvConf = false then it will stop dynamically creating and destroying resolv.conf.If you put this in your resolv.conf,nameserver <your ip gateway or DNS server>(eg. Nameserver 192.168.86.1)This isn’t an archwsl issue, this is a wsl2 issue. If you use a VPN, enabling and disabling the VPN will bork your WSL networking. Forcing a static resolv.conf that points to your gateway helped me, at least.From: Alexander-HuangSent: Wednesday, September 30, 2020 9:41 AMTo: yuk7/ArchWSLCc: SubscribedSubject: Re: [yuk7/ArchWSL] Internet or Network suddenly gone. Gibbrish /etc/resolv.conf file (#140) Could you please paste your resolv.conf of wsl1?I have the same issue after switching to wsl2.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Alexander-Huang** [comment]
> Currently there is a bug on Insider WSL2, where the Internet connection gets disconnected after x time

emmm,although I'm not a windows insider, I'm facing a bug sounds similar.But for me,the network of wsl and windows disconnects together when I try uploading or downloading something in archwsl.

However,the ping and curl send correct feedback and they don't cut off windows's network connection.

**Comment by danielwagn3r** [comment]
I've recognized that the `/etc/resolv.conf` is missing the `search` entry so that resolving domain names of local machines is only possible with FQDNs despite the setting being set in windows.

**Comment by danielwagn3r** [comment]
Relates to https://github.com/Microsoft/WSL/issues/701
