### ISSUE TITLE
Starting Systemd automatically

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [yuk7/ArchWSL#164]
Hi,

Is there a way to start thee Systemd automatically while booting WSL2? Both subsystemctl and genie require users to execute them manually after boot. Is there a way to start them automatically without calling the commands through .zshrc/.bashrc?

Also, What happened to ArchWSL2? I taught it was pretty stable.

**Comment by yuk7** [comment]
ArchWSL2 has been discontinued due to a bug found that is difficult to fix.
I'm currently researching if we can do the same thing using other methods.
Microsoft's init is a difficult road because it's proprietary.

**Comment by yuk7** [comment]
I used to aim to work with all shells and programs.  However, it will be easier to some extent if it works only with a specific shell such as bash or zsh.

**Comment by nisarg-ujjainkar** [comment]
Could you tell me what the bug is? I have been using it for a couple of months now, and it has a lot of things. Do I need to migrate to AwchWSL?

**Comment by yuk7** [comment]
The most serious bug is a mounting bug that causes the file update to fail.
If possible, I think it is better to migrate to ArchWSL.

(However, I'm still using ArchWSL2 personally and haven't completely migrated.)

**Comment by nisarg-ujjainkar** [comment]
Ok, can I use these scripts to start systemd at boot?
https://github.com/yuk7/container-systemd-init-tool

**Comment by yuk7** [comment]
It can't be used.
 It is buggy.  Also, it's not intended for manual use.

**Comment by nisarg-ujjainkar** [comment]
ok, thanks.

**Comment by gifnksm** [comment]
FYI, I use [genie-systemd] to launch systemd.
I haven't encountered any major problems so far, and I'm using it comfortably.

My custom PKGBUILD file is [here](https://github.com/gifnksm/pkgbuild/tree/master/genie-systemd).

[genie-systemd]: https://github.com/arkane-systems/genie

**Comment by nisarg-ujjainkar** [comment]
> FYI, I use [genie-systemd](https://github.com/arkane-systems/genie) to launch systemd.
> I haven't encountered any major problems so far, and I'm using it comfortably.
> 
> My custom PKGBUILD file is [here](https://github.com/gifnksm/pkgbuild/tree/master/genie-systemd).

Can I execute windows commands like `code` or `explorer.exe` when inside systemd environment?

**Comment by gifnksm** [comment]
> Can I run Windows commands such as `code` and `explorer.exe` in a systemd environment?

Yes, you can launch `explorer`  but by executing `/mnt/c/Windows/explorer.exe`. 

Since `genie` removes Windows paths from `PATH` environment variable by default, you must specify a full path starting with `/mnt/<drive letter>/` to execute programs in Windows paths.
This behavior can be changed by setting `clone-path=true` in `/etc/genie.ini`.
See [genie README](https://github.com/arkane-systems/genie#configuration-file) for details.

**Comment by PhyX-Meow** [comment]
Use something like `wsl -d Arch -- genie -s`

**Comment by lungothrin** [comment]
Maybe this one is what you want
Launch systemd-enabled shell directly from start menu
https://github.com/lungothrin/bottled-shell

**Comment by nisarg-ujjainkar** [comment]
There is also this [wsl-distrod](https://github.com/nullpo-head/wsl-distrod). It automatically starts systems when wsl boots. So far, I have not encountered any problems which I encountered with genie or other such tools.

**Comment by lungothrin** [comment]
I stop using wsl-distrod as it failed to start user.slice in Arch Linux. but anyway good to know

**Comment by kevincrans** [comment]
If you use Ubuntu, it seems to be fixed, maybe the developer can use this: https://bugs.launchpad.net/ubuntu/+source/wsl-setup/+bug/1962556

**Comment by sigurdo** [comment]
You can also start systemd automatically through Windows Task Scheduler.

Simply press "Create basic task" and follow the wizard. For trigger I use "When I log on" and the action is `wsl` with arguments `-u root -- <path to subsystemctl> start`. For me, `<path to subsystemctl>` is `/home/sigurd/.cargo/bin/subsystemctl`, since I installed subsystemctl with cargo as my own user (`sigurd`).

If you have a laptop, I also highly recommend to disable "Start the task only if the computer is on AC power" under "Conditions". This option is not in the wizard, and has to be done by modifying the task properties afterwards.

**Comment by rollingmoai** [comment]
Systemd support is now available in WSL!
https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/

@yuk7 You can mark this as resolved now
