### ISSUE TITLE
Is there any way to change the Arch.exe folder 

### ISSUE THREAD

**Issue by kidush** [yuk7/ArchWSL#24]
I've just installed Arch.exe on the Download folder 🤦‍♂️ 
and I tried to move the folder to my AppData, but for some reason it didn't work,

Do you have any ideas?

**Comment by yuk7** [comment]
Normally,You can't move the installed folder,because WSL instance using registry key.
Please uninstall and re-install it.
1. Run `wslconfig /u Arch`command to uninstall instance.
2. Delete rootfs and temp folder.
3. Re-install.

or manipulate registry key.
(HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss\{LxUID})

**Comment by kidush** [comment]
Thank you @yuk7 

I've changed the registry key and It worked properly!

**Comment by qwelias** [comment]
@yuk7 please put it in the WIki

**Comment by ricardo-dlc** [comment]
I want to change my installation folder, if I unregister the instance, do I will lost my data? I mean, everything that is inside the Arch Linux filesystem, or can I just use the same file for a new installation?
