### ISSUE TITLE
ldconfig: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

### ISSUE THREAD

**Issue by izeroo** [yuk7/ArchWSL#248]
**Describe the issue**

ldconfig: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

**To Reproduce**

Just simply pacman -Syu, and you'll see that sometimes.

**Expected behavior**

**Screenshots**

**Enviroment:**
 - Windows build number: [10.0.22000.194] (Type `ver` at a Command Prompt)
 - Security Software: [none]
 - WSL version 1/2: [WSL2]
 - ArchWSL version [21.8.28.0]
 - ArchWSL Installer type zip/appx/other clean/update [zip]
 - Launcher version [wsldl2, version 21082800] (Type `Arch.exe version` at a Command Prompt)

**Additional context**

**Comment by PhyX-Meow** [comment]
Actually this is not relate to Arch, nor ArchWSL. It's caused by `libcuda.so` in your `C:\Windows\System32\lxss\lib\` folder not a symbolic link, which is installed by nvidia driver. One solution to fuck the warning is delete `libcuda.so` and `libcuda.so.1` and use
make symbolic link to `libcuda.so.1.1`. Command line: `mkink <target file> <source file>`. Note the command not work in powershell, you shall use `cmd.exe`.
:)

**Comment by izeroo** [comment]
Thanks. Solved.
