### ISSUE TITLE
No lxuid in Windows 10 1709

### ISSUE THREAD

**Issue by corelon** [yuk7/ArchWSL#45]
Hi,

I am using Windows 10 1709.
I down Arch.zip and unzip it in a folder in my Downloads folder (\Downloads\WSLArch)
I follow the steps provided in the wiki and everything seems to be working fine other than starting Arch.exe as Admin to install.
It starts normally (a command prompt is starting) but when I do Arch.exe get --lxuid I get an empty line.
I found this out as I tried to create an entry for this in Cmder.

Any help would be greatly appreciated.

**Comment by corelon** [comment]
Windows build number: 10.0.16299.547
ArchWSL version: 18081100
Launcher version: 18080900

Note: please disregard the installation part, as  I may have done it in the past. The problem with lxuid still is valid though. When I do Arch.exe get --lxuid I get nothing.

**Comment by yuk7** [comment]
Ok...
I checked `Arch.exe get --lxuid` command on my computer(1803),but it is working...
Can you retry by giving administrator privileges?
and Please give me screenshot of regedit `HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss`...

**Comment by corelon** [comment]
![wsl_arch_issue](https://user-images.githubusercontent.com/49140/44398106-58751b00-a54b-11e8-9db6-ca03bd9dc88a.PNG)

As for Arch.exe get --lxuid it is still not working
Regarding the installation I had indeed installed it on a different location. Tried the Arch.exe in that location as well and still getting the same issue with lxuid for some reason.

**Comment by abelsromero** [comment]
It could be that path is longer than that Arch.exe supports, if I read the code correctly, the path cannot be longer than 25 chars (https://github.com/yuk7/wsldl/blob/864093bd9696a8372ed6753704804eb079760b42/wsld.h#L92).

Since @corelon installed in under `Downloads` I assume the full path is something like "C:\Users\USERNAME\Donwloads\Arch". Even with a username of 1 character, it's already 26 characters.

`RegQueryValueExW` already returns ERROR_MORE_DATA if the buffer was not big enough. So even if after increasing the size, that's not big enough, we should be able to capture the error and report back to users.

**Comment by abelsromero** [comment]
Forget what I said, I was assuming something else... not really sure what is failing but did a poc to obtain lxuid a bit differently and it also provides some extra feedback. I could not reproduce it.

Could you try to run the poc?
NOTE it is important to rename the exe exactly as your current installation, but you can place it everywhere.

[Arch.zip](https://github.com/yuk7/ArchWSL/files/2389793/Arch.zip)

Modified code is here:https://github.com/abelsromero/wsldl/blob/issue_45/wsld.h

**Comment by corelon** [comment]
Apologies for the very delayed answer.
Tried with the latest version of Arch.exe and still havinig the same issue. I am guessing it should be a problem with my configuration.
As it does not really have any effect on my day to day I am currently closing the issue.
Thank you very much for the help and will reopen if I notice any glitch on the OS operation.
