### ISSUE TITLE
update linux failed

### ISSUE THREAD

**Issue by Frefreak** [yuk7/ArchWSL#55]
**Describe the issue**
Hello,
When trying to update linux package, during post-transaction hooks I got lots of errors like the following and kernel version still 4.4 after rebooting/restarting LxssManager
```
bsdcpio: VERSION: large inode number truncated: Numerical result out of range
```
Is this expected or is there something wrong with my installation?

**To Reproduce**
```
sudo pacman -S linux
```

**Expected behavior**
exit code 0 and kernel version be 4.18 after reboot windows or restarting LxssManager

**Enviroment**:

Windows build number: Microsoft Windows [Version 10.0.17134.319]
ArchWSL version: 18081100
Launcher version: wsldl, version 18080900

Other packages seem to work fine.

**Comment by yuk7** [comment]
Please fill issue template:

**Please fill out the below information:**
**Describe the issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Enviroment:**
 - Windows build number: [e.g. 10.0.17134.228] (Type `ver` at a Command Prompt)
 - ArchWSL version [e.g. 18081100] (version of zip)
 - Launcher version [e.g. 18080900] (Type `Arch.exe version` at a Command Prompt)

**Additional context**
Add any other context about the problem here.

**Comment by Frefreak** [comment]
Sorry, updated.

**Comment by Frefreak** [comment]
It makes sense... So it's probably safe to ignore, for now.
Thanks for you answer.
