### ISSUE TITLE
Cannot mount the drive with metadata

### ISSUE THREAD

**Issue by goduck777** [yuk7/ArchWSL#58]
For the latest WSL in Windows 10, the file permissions can be handled using DrvFs through metadata switch.

https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/

However, after trying the command in Arch WSL, the metadata function is still not working, nor is it shown in `mount -l` command result.

**Comment by yuk7** [comment]
I tried it on ArchWSL 18081100 in Windows 10 17134.320,
but it works.

![mount_metadata](https://user-images.githubusercontent.com/29954265/46384366-7019f480-c6f0-11e8-917f-6865cd23d052.png)

**Comment by yuk7** [comment]
Could you fill the issue template? :

**Please fill out the below information:**
**Describe the issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Enviroment:**
 - Windows build number: [e.g. 10.0.17134.228] (Type `ver` at a Command Prompt)
 - ArchWSL version [e.g. 18081100] (version of zip)
 - Launcher version [e.g. 18080900] (Type `Arch.exe version` at a Command Prompt)

**Additional context**
Add any other context about the problem here.

**Comment by goduck777** [comment]
Thank you for quick response. I realized I need to reboot the system to make it work. simply umount and mount does not help.

**Comment by yuk7** [comment]
Ok.
