### ISSUE TITLE
Issues with X

### ISSUE THREAD

**Issue by ryaniskira** [yuk7/ArchWSL#68]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**

Any attempt to use X Forwarding fails (any attempt to run any software with a GUI complains about not being able to connect to a display), but if Ubuntu WSL is running and connected to a remote server, ArchWSL can use X-Forwarding just fine. Another thing I have noticed that even though I have the display variable in .bashrc, local software with a GUI will refuse to run until I manually export the display variable regardless if another WSL distro is running.

**To Reproduce**
Set up the prerequisites for using X on WSL (install an X server, make sure display variable is set, etc etc) then attempt to use anything that requires X (Geany for example).

**Expected behavior**
X to work.

**Screenshots**
[Here is a video of the issue](https://youtu.be/iuCJT3Qvu0g)

**Enviroment:**
 - Windows build number: 10.0.18305.1003]
 - ArchWSL version 19010200
 - Launcher version 18122700

**Additional context**
As mentioned before I have all the requisites for X Forwarding to work via WSL. X Server (Vcxsrv), the relevant variable exported, the relevant configs in /etc/ssh/ssh_config, etc etc.

**Comment by elswerky** [comment]
type in terminal or ~/.bashrc
export DISPLAY=:0

**Comment by yuk7** [comment]
Yes, in my environment it works correctly by adding it to bashrc.

**Comment by ryaniskira** [comment]
It's in my bashrc. It's setup exactly how I have my Ubuntu WSL setup.

**Comment by yuk7** [comment]
I cleanly installed and reconfirmed but the same problem could not be confirmed...
Have you set up bashrc correctly?
`echo $DISPLAY`

**Comment by elswerky** [comment]
@yuk7  do you have a telegram account ??

**Comment by KeAWang** [comment]
I'm having the same issue. I have `DISPLAY=:0` and installed `xorg-apps` and `xorg-server` as instructed on the Arch wiki. I also have xming set up which works fine with ubuntu. However, I cannot forward anything with the Arch WSL to xming

**Comment by PhilDim1** [comment]
I needed to specify my ip address in the DISPLAY (ie. DISPLAY=192.168.xx.xx:0). I actually needed to do this with Ubuntu as well. I've never gotten it to work with just =:0

**Comment by KeAWang** [comment]
It still doesn't work for me unfortunately. I tried with `DISPLAY=$(hostname -i):0` without any luck

**Comment by snowman** [comment]
Have you fix the problems? I have the same issue.

**Comment by snowman** [comment]
```
Follow steps:
1. Run "XLaunch.exe" with "Display number: 0", and checks ON "No Access Control"
  (The "No Acess Control" must turn on, otherwise it would NOT work)
2. Make sure you are running WSL 2 version:
   $ wsl -l -v
   NAME      STATE           VERSION
 * Ubuntu    Stopped         2
   Arch      Stopped         2

   If not, run below:
   $ wsl --set-version Arch 2
3. Open ArchWSL, then run following command:
   $ cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }'
   172.24.240.1
   $ export DISPLAY=172.24.240.1:0
4. Test GUI
   ## Install xeyes
   ## $ yes | pacman -S xorg-xeyes
   $ xeyes
   ## toda!! volia~
```

**Comment by snowman** [comment]
Follow steps:
1. Run "XLaunch.exe" with `Display number: 0`, and checks ON `No Access Control`
  (The `No Acess Control` MUST TURN ON, otherwise it would NOT work)
2. Make sure you are running `WSL 2` version:
```cmd
   $ wsl -l -v
   NAME      STATE           VERSION
 * Ubuntu    Stopped         2
   Arch      Stopped         2
```

   If not, run:
```cmd
   $ wsl --set-version Arch 2
```
3. Open Arch WSL with `arch`, then run following command:
```sh
   $ cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }'
   172.24.240.1
   $ export DISPLAY=172.24.240.1:0
```
4. Test GUI
```sh
   ## Install xeyes
   ## $ yes | pacman -S xorg-xeyes
   $ xeyes
```
5. toda!! volia~ You should see eyes appear on your screen.

You can also add the script into your ".bashrc" file by running command:
```sh
$ cat <<EOF >> ~/.bashrc
export DISPLAY="\$(cat /etc/resolv.conf | grep nameserver | awk '{ print \$2 }'):0"
EOF
```

**Comment by snowman** [comment]
Follow steps to fix WSL2 with X11-server Xming issue:
1. Run "XLaunch.exe" with `Display number: 0`, and checks ON `No Access Control`
  (The `No Acess Control` MUST TURN ON, otherwise it would NOT work)
2. Make sure you are running `WSL 2` version:
```cmd
   $ wsl -l -v
   NAME      STATE           VERSION
 * Ubuntu    Stopped         2
   Arch      Stopped         2
```

   If not, run:
```cmd
   $ wsl --set-version Arch 2
```
3. Open Arch WSL with `arch`, then run following command:
```sh
   $ cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }'
   172.24.240.1
   $ export DISPLAY=172.24.240.1:0
```
4. Test GUI
```sh
   ## Install xeyes
   ## $ yes | pacman -S xorg-xeyes
   $ xeyes
```
5. toda!! volia~ You should see eyes appear on your screen.

You can also add the script into your ".bashrc" file by running command:
```sh
$ cat <<EOF >> ~/.bashrc
export DISPLAY="\$(cat /etc/resolv.conf | grep nameserver | awk '{ print \$2 }'):0"
EOF
```

**Comment by snowman** [comment]
Follow steps to fix WSL2 with X11-server Xming issue:
1. Run "XLaunch.exe" with `Display number: 0`, and checks ON `No Access Control`
  (The `No Acess Control` MUST TURN ON, otherwise it would NOT work)
2. Make sure you are running `WSL 2` version:
```cmd
   $ wsl -l -v
   NAME      STATE           VERSION
 * Ubuntu    Stopped         2
   Arch      Stopped         2
```

   If not, run:
```cmd
   $ wsl --set-version Arch 2
```
3. Open Arch WSL with `arch`, then run following command:
```sh
   $ cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }'
   172.24.240.1
   $ export DISPLAY=172.24.240.1:0
```
4. Test GUI
```sh
   ## Install xeyes
   ## $ yes | pacman -S xorg-xeyes
   $ xeyes
```
5. toda!! volia~ You should see eyes appear on your screen.

You can also add the script into your ".bashrc" file by running command:
```sh
$ cat <<EOF >> ~/.bashrc
export HOST_IP="\$(cat /etc/resolv.conf | grep nameserver | awk '{ print \$2 }')"
export DISPLAY="\$HOST_IP:0"
EOF
```

**Comment by snowman** [comment]
Follow steps to fix WSL2 with X11-server Xming issue:
1. Run "XLaunch.exe" with `Display number: 0`, and checks ON `No Access Control`
  (The `No Acess Control` MUST TURN ON, otherwise it would NOT work)
2. Make sure you are running `WSL 2` version:
```cmd
   $ wsl -l -v
   NAME      STATE           VERSION
 * Ubuntu    Stopped         2
   Arch      Stopped         2
```

   If not, run:
```cmd
   $ wsl --set-version Arch 2
```
3. Open Arch WSL with `arch`, then run following command:
```sh
   $ cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }'
   172.24.240.1
   $ export DISPLAY=172.24.240.1:0
```
4. Test GUI
```sh
   ## Install xeyes
   ## $ yes | pacman -S xorg-xeyes
   $ xeyes
```
5. tada!! volia~ You should see eyes appear on your screen.

You can also add the script into your ".bashrc" file by running command:
```sh
$ cat <<EOF >> ~/.bashrc
export HOST_IP="\$(cat /etc/resolv.conf | grep nameserver | awk '{ print \$2 }')"
export DISPLAY="\$HOST_IP:0"
EOF
```

**Comment by snowman** [comment]
see https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999

**Comment by snowman** [comment]
see [Unable to accessing Windows applications from WSL](https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999)
